---
title: "Article search"
output:
  distill::distill_article

---


```{r setup, include=FALSE}
source("readdata.R", local = knitr::knit_global())
```

Total number of SADs **`r nrow(table1)`**. Apply the filters to reorder or  enter any word in the search box. The link icon will direct you to the publisher website to get the full article.

```{r include=FALSE, layout="l-page"}
library(crosstalk)
sd <- SharedData$new(table1)
```


```{r echo=FALSE, layout="l-page"}
bscols(

 filter_slider("year", "Publication year", sd, ~pub_year, round = TRUE),
 filter_select("cropname", "Crop name", sd, ~crop),
  filter_select("pathogen", "Pathogen species name", sd, ~pathogen)

)

```


```{r echo=FALSE, layout="l-page"}
library(DT)
datatable(sd, 
          escape = FALSE,
          class = 'cell-border stripe',
        rownames = FALSE, colnames = c('Year','Crop', 'Pathogen',  'Pathogen group', 'Organ', 'citation', 'Ref'), 
          options = list(
  pageLength = 12,
  fontSize = 12,
  lengthMenu = c(25, 50, 100, 500 )
))%>%
formatStyle(
  c('pub_year', 'crop',  'pathogen', 'pathogen_group', 'organ',   'citation', 'weblink'),
  fontSize = '130%')

```




