---
title: "Diagram of plant disease severity"
output: 
  flexdashboard::flex_dashboard:
    css: style.css
    logo: logo-sad.gif
---

<script src="https://use.fontawesome.com/682f97eaed.js"></script>


```{r, include=FALSE}
library(ggplot2)
library(plotly)
library(readr)
library(plyr)
library(dplyr)
library(tidyr)
```


```{r, include=FALSE}
# Reading the data 
dat_sad <- read_csv ("dat_sad.csv")
attach(dat_sad)
dat_sad$citation <- paste(author, pub_year)
dat_sad$study_diag <- with(dat_sad, interaction(study, diag_id))
dat_sad$citation_diag <- with(dat_sad, interaction(citation, diag_id))
detach(dat_sad)

# aggregate by individidual studies
dat_sad <- group_by(dat_sad, study)
dat_sad1 <- filter(dat_sad, row_number()==1 )
```

```{r, include=FALSE}
dat_sad2 <- ungroup(dat_sad1)
table1 <- select(dat_sad2, pub_year, crop, pathogen, pathogen_group, journal, country, lang, pub_type, citation, link1, link, link2)
table1 <- arrange(table1, -pub_year)
table1 <- unite(table1, weblink, link1, link, link2, sep = "")

```


Summary Plots {data-icon="fa-bar-chart"}
=====================================

Column {.tabset data-width=350px}
----------------------------------

### <i class="fa fa-home" aria-hidden="true"></i> About 

**What is SADBank?**

**SAD<i class="fa fa-leaf" aria-hidden="true"></i>Bank** is a database of Standard Area Diagrams (SADs) of plant disease severity. The database supplements a systematic review research article submitted to *Phytopathology* and will be updated as more SADs are published in the literature. 

**How to use it? **

The main two pages are [Summary](#summary-plots) and [Tables](#tables). In summary plots, characteristics related to the publication and the SAD are graphically displayed. In Tables, there are three tables with tabuluar information for the 1) publication; 2) SAD characteristics and 3) the validation approach. A weblink to access the publication is provided in the last column of each table.

**What are SADs?**

Also known as disease diagrams or diagrammatic scales, SADs are a set of pictorial representation  of disease symptoms and/or signs in a plant organ. Each diagram depicts a percent diseased area. They are designed in a wide range of styles. 
**How are SADs used?**

SADs are tools used during or prior to visual assessments of disease severity to "calibrate" a rater's eye and improve accuracy, precision and reliability of the estimates. During estimation, the rater assigns a percent value that should be as close as much to "actual" values. The diagrams in the SADs serve as a guide for interpolation. In most studies, SADs have proven of value especially for innately inaccurate raters and certain symptoms/signs that are more difficult to evaluate.

### <i class="fa fa-bar-chart" aria-hidden="true"></i> Plotted variables description

**Description of variables**

- **Articles/year** -
Number of articles published per year and language of the publication where EN = english, ES = spanish and PT = Portuguese.

- **N. of specimens** - 
Frequency of the number of specimens (leaf, fruit, stalk, etc.) collected in the field or experimental plots and analyzed to determine the range of actual (true) disease severity, usually using digital analysis.

- **Actual severity estimation** -
Frequency of the approach used to determine the actual severity values in the samples, including digital image analysis tools or instruments such as leaf area meater and planimeter.

- **N. of diagrams** - 
Number of diagrams (severity values) depicting a percent diseased area in the SAD set.

- **Min sev** - 
Frequency of the minimum non-zero severity depicted in the SAD.

- **Max sev** -
Frequency of the maximum severity depicted in the SAD.

- **SAD color** -
Frequency of the color scheme used to depict the SAD such as black-white, 2-color, true-color, etc.

- **Max sev vs. ndiag** -
Scatterplot for the relationship between the number of diagrams and the maximum severity depicted in the SAD.

- **Country** -
Map depicting the number of studies by country of the research group conducting the study.


### <i class="fa fa-user" aria-hidden="true"></i> Credits

**SAD<i class="fa fa-leaf" aria-hidden="true"></i>Bank** is curated by Prof. Emerson Del Ponte, coordinator of the [Epidemiology Lab](http://www.dfp.ufv.br/epidemiology) of the Universidade Federal de Viçosa, Brazil. People who are key collaborators and support the development of the SAD project are:

- Dr. Sarah J. Pethybridge, [EVADE](http://evade.pppmb.cals.cornell.edu) Lab, Cornell University, USA

- Dr. Sami J. Michereff, Universidade Federal Rural de Pernambuco, Recife, Brazil

- Franklin J. Machado, Graduate Student Epidemiology Lab UFV


Column {.tabset}
----------------------------------

### Articles/year


```{r, echo=FALSE}
library(ggplot2)
library(plotly)

g_artigos <- ggplot(dat_sad1, aes(factor(pub_year), fill=lang)) + geom_bar() +
         scale_y_continuous(breaks=seq(0, 12, 1), expand=c(0.02, 0))+
       xlab("Year")+ ylab("Number of articles")+
  theme_minimal()+
       theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position="none")+
         scale_fill_manual(values = c("steelblue","brown", "limegreen"))+
  labs(fill = "Language")
      
(gg <- ggplotly(g_artigos))
``` 

### N. of samples

```{r}
n_dev <- subset(dat_sad2, n_dev <1000, select = n_dev)
g_nsamples <- ggplot(n_dev, aes(x=n_dev))+
geom_histogram(binwidth=50, color = "white", fill = "SteelBlue")+ 
 xlab("Number of samples")+
 ylab("Frequency")+
 scale_x_continuous(breaks=c(0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500))+
  theme_minimal()
(gg <- ggplotly(g_nsamples, tooltip = c("count")))



```


### Actual severity estimation

```{r}
library(RColorBrewer)
dat_sad1$sev_quant2 <- with(dat_sad1, reorder(sev_quant, sev_quant, function(x) length(x)))
g_soft <- ggplot(dat_sad1, aes(sev_quant2, fill=sev_quant2)) +
            geom_bar() + coord_flip()+
            scale_y_continuous(breaks=seq(0, 100, 2),
                               expand=c(0, 0))+
            xlab("")+ ylab("Number of studies")+
  theme_minimal()+
            theme(legend.position="none")+
 scale_fill_hue("clarity", direction = -1)
           
(gg <- ggplotly(g_soft, tooltip = c("count")))

```

### N. of diagrams
```{r}


g_ndiag<- ggplot(dat_sad1, aes(x=n_diagrams))+
geom_histogram( binwidth=1, color = "white", fill = "steelblue")+ 
 xlab("Number of diagrams in the SAD")+
 ylab("Frequency")+
 scale_x_continuous(breaks=c(1:12))+
theme_minimal()
(gg <- ggplotly(g_ndiag, tooltip = c("count")))
```

### Min. sev

```{r}
g_minsev <- ggplot(dat_sad2, aes(x=min_sev))+
geom_histogram(fill = "steelblue", color = "white")+ 
 xlab("Minimum severity (%)")+
 ylab("Frequency")+
 scale_x_continuous(breaks=c(0:11))+
  theme_minimal()
(gg <- ggplotly(g_minsev))
```

### Max. sev

```{r}
g_maxsev <- ggplot(dat_sad2, aes(x=max_sev))+
geom_histogram(fill = "steelblue", color = "white")+ 
 xlab("Maximum severity (%)")+
 ylab("Frequency")+
 scale_x_continuous(breaks=c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ))+
 theme_minimal()
(gg <- ggplotly(g_maxsev, tooltip = c("count")))
```

### SAD color

```{r}
dat_sad2$col_type2 <- with(dat_sad2, reorder(col_type, col_type, function(x) length(x)))
g_color <- ggplot(dat_sad2, aes(col_type2, fill=diag_type)) +
            geom_bar() + coord_flip()+
            scale_y_continuous(breaks=seq(0, 100, 5), expand=c(0.02, 0))+
            xlab("")+ ylab("Number of SADs")+
 theme_minimal()+
            theme(legend.position = "none")+ scale_fill_manual(values = c("steelblue", "limegreen"))
 (gg <- ggplotly(g_color))
```

### Max sev vs. ndiag

```{r}
g_rel1 <- ggplot(dat_sad2, aes(max_sev, n_diagrams))+
geom_point(aes(alpha=0.5), size=3, colour = "limegreen",
            position = position_jitter(width=.2))+
 stat_smooth(colour="steelblue", size=0.75, alpha=0.1)+
  theme_minimal()+
 theme(legend.position = "none")+
 scale_y_continuous(breaks=c(1:12 ))+
 ylab("Number of diagrams")+
 xlab("Maximum severity (%)")
(gg <- ggplotly(g_rel1))


```


### Country

```{r}
library(plotly)

df <- read.csv('country.csv')

# light grey boundaries
l <- list(color = toRGB("grey"), width = 0.5)

# specify map projection/options
g <- list(
  showframe = FALSE,
  showcoastlines = TRUE)


plot_ly(df, z = SAD, text = COUNTRY, locations = CODE, type = 'choropleth', showscale = FALSE,
        color = SAD, colors = c("white", "steelblue"), marker = list(line = l), title = '') %>%
  layout(title = '<br>Country of the authorship of studies</br> on the development and validation of SADs',
         geo = g)

```

Tables {data-icon="fa-table"}
=====================================


Column {.tabset }
-------------------------------------
 
### Study information


```{r}
library(magrittr)
library(DT)

datatable(table1,
          escape = FALSE,
          class = 'cell-border stripe',
          rownames = FALSE, colnames = c('Publication year','Crop', 'Pathogen', 'Pathogen group', 'Journal', 'Country', 'Language', 'Publication type',  'Reference', 'Link'), 
          options = list(
  pageLength = 25,
  fontSize = 12,
  lengthMenu = c(10, 25, 50, 100 )
))%>%
formatStyle(
  c('crop', 'pathogen', 'pathogen_group', 'pub_year','journal', 'country', 'lang', 'pub_type', 'citation', 'weblink'),
  fontSize = '90%')

```

   
### SAD characteristics

```{r, include=FALSE}
library(plyr)
library(dplyr)
dat_sad2 <- ungroup(dat_sad1)
table1 <- select(dat_sad2, pub_year, crop, dis_name, pathogen, n_diag, organ, diag_type, col_type, n_diagrams, min_sev, max_sev, citation, link1, link, link2)

table1 <- arrange(table1, -pub_year)
table1 <- unite(table1, weblink, link1, link, link2, sep = "")


```

```{r}
datatable(table1, 
          escape = FALSE,
          class = 'cell-border stripe',
        rownames = FALSE, colnames = c('Publication year','Crop', 'Disease name', 'Pathogen', 'N. of sets','Organ', 'Design type', 'Diagram color', 'N. of diagrams', 'Min. Severity', 'Max. Severity', 'Reference', "Link"), 
          options = list(
  pageLength = 25,
  fontSize = 12,
  lengthMenu = c(10, 25, 50, 100 )
))%>%
formatStyle(
  c('pub_year', 'crop','dis_name','pathogen', 'n_diag', 'organ', 'diag_type', 'col_type', 'n_diagrams', 'min_sev', 'max_sev', 'citation', 'weblink'),
  fontSize = '90%')
```


### SAD validation approach 

```{r, include=FALSE}
library(plyr)
library(dplyr)
dat_sad2 <- ungroup(dat_sad1)
table1 <- select(dat_sad2, pub_year, crop, dis_name, pathogen, validation, stat, coefs, n_valid, citation, link1, link, link2)
table1 <- arrange(table1, -pub_year)
table1 <- unite(table1, weblink, link1, link, link2, sep = "")


```

```{r}

datatable(table1, 
          escape = FALSE,
          class = 'cell-border stripe',
                  rownames = FALSE, colnames = c('Publication year','Crop', 'Disease name', 'Pathogen', 'Validation approach', 'Statistics', 'Reported coefficients', 'N. of specimens assessed', 'Reference', 'Link'), 
          options = list(
  pageLength = 25,
  fontSize = 12,
  lengthMenu = c(10, 25, 50, 100 )
))%>%
formatStyle(
  c('pub_year', 'crop','dis_name','pathogen', 'validation', 'stat', 'coefs', 'n_valid', 'citation', 'weblink'),
  fontSize = '90%')

```






